server:
  port: 9092

spring:
  application:
    name: gestion_usuarios
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dpg-cq7d6j0gph6c73ct0ao0-a.oregon-postgres.render.com:5432/gestion_citas 
    username: grupo4_dsw
    password: jyidc7vQat5NUV7jhNXPTbWcEPPx4lsn
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka