server:
  port: 8081

spring:
  application:
    name: SpringMsSisvitaGateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: carreras
          uri: 'http://localhost:9091'
          predicates:
            - Path=/api/v1/carreras/**
            
        - id: gestion-usuarios-service
          uri: 'http://localhost:9092'
          predicates:
            - Path=/api/v1/gestion_usuarios/administradores/**

eureka:
  client:
    register-with-eureka: false